-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: PROD.TEST
-- ============================================================

USE DATABASE PROD;
USE SCHEMA TEST;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP STAGE IF EXISTS "PROD"."TEST"."PROD_STAGE";
DROP TASK IF EXISTS "PROD"."TEST"."PROD_TASK";
DROP STREAM IF EXISTS "PROD"."TEST"."PROD_USERS_STREAM";
DROP VIEW IF EXISTS "PROD"."TEST"."PROD_USERS_VIEW";
DROP ROW ACCESS POLICY IF EXISTS "PROD"."TEST"."PROD_ROW_POLICY";
DROP TABLE IF EXISTS "PROD"."TEST"."PROD_TEMP_DATA";
DROP TABLE IF EXISTS "PROD"."TEST"."PROD_ONLY_TABLE";

-- ------------------------------------------------------------
-- ALTER COLUMNS
-- ------------------------------------------------------------

ALTER TABLE "PROD"."TEST"."USERS" DROP COLUMN "STATUS";
ALTER TABLE "PROD"."TEST"."USERS" DROP COLUMN "PHONE";
ALTER TABLE "PROD"."TEST"."USERS" ALTER COLUMN "EMAIL" SET DATA TYPE VARCHAR(255);
ALTER TABLE "PROD"."TEST"."USERS" ALTER COLUMN "NAME" SET DATA TYPE VARCHAR(100);
ALTER TABLE "PROD"."TEST"."ORDERS" ALTER COLUMN "AMOUNT" SET DATA TYPE NUMBER(10,2);
ALTER TABLE "PROD"."TEST"."ORDERS" ALTER COLUMN "ORDER_DATE" SET DATA TYPE DATE;
CREATE OR REPLACE SEQUENCE "PROD"."TEST"."USER_SEQUENCE"
  START = 1
  INCREMENT = 1
  NOORDER;


-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE SEQUENCE "PROD"."TEST"."USER_ID_SEQUENCE"
  START = 1
  INCREMENT = 1
  NOORDER;

CREATE OR REPLACE MASKING POLICY "PROD"."TEST"."EMAIL_MASK_POLICY" AS (VAL VARCHAR) 
RETURNS VARCHAR ->
CASE
        WHEN CURRENT_ROLE() = 'ACCOUNTADMIN'
            THEN val
        ELSE '********'
    END;

CREATE OR REPLACE ROW ACCESS POLICY "PROD"."TEST"."DEV_ROW_POLICY" AS (EMAIL VARCHAR) 
RETURNS BOOLEAN ->
CURRENT_USER() = EMAIL;

CREATE OR REPLACE ROW ACCESS POLICY "PROD"."TEST"."USER_ROW_POLICY" AS (EMAIL VARCHAR) 
RETURNS BOOLEAN ->
CURRENT_USER() = email;

CREATE OR REPLACE FILE FORMAT "PROD"."TEST"."MY_CSV_FORMAT"
  TYPE = CSV
  SKIP_HEADER = 1
;

CREATE OR REPLACE STAGE "PROD"."TEST"."DEV_STAGE"
  DIRECTORY = (ENABLE = FALSE);

CREATE OR REPLACE STAGE "PROD"."TEST"."MY_STAGE"
  DIRECTORY = (ENABLE = FALSE);

CREATE OR REPLACE TABLE "PROD"."TEST"."DEV_ONLY_TABLE" (
	ID NUMBER(38,0),
	DESCRIPTION VARCHAR(500),
	CREATED_AT TIMESTAMP_NTZ(9)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
;

CREATE OR REPLACE TRANSIENT TABLE "PROD"."TEST"."DEV_TEMP_DATA" (
	ID NUMBER(38,0),
	VALUE VARCHAR(16777216)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
;

CREATE OR REPLACE TRANSIENT TABLE "PROD"."TEST"."TEMP_USERS" (
	ID NUMBER(38,0),
	NAME VARCHAR(16777216)
)
  DATA_RETENTION_TIME_IN_DAYS = 1
;

CREATE OR REPLACE EVENT TABLE "PROD"."TEST"."EVENT_LOG"
  DATA_RETENTION_TIME_IN_DAYS = 1
  MAX_DATA_EXTENSION_TIME_IN_DAYS = 14;

CREATE OR REPLACE VIEW "PROD"."TEST"."DEV_USERS_VIEW"(
	ID,
	NAME
) as
SELECT
    ID,
    NAME
FROM USERS;

CREATE OR REPLACE RECURSIVE VIEW "PROD"."TEST"."EMPLOYEE_HIERARCHY"(
	EMPLOYEE_ID,
	EMPLOYEE_NAME,
	MANAGER_ID
) as
SELECT
    id,
    name,
    manager_id
FROM users;

CREATE OR REPLACE MATERIALIZED VIEW "PROD"."TEST"."USER_COUNT"(
	TOTAL_USERS
) as
SELECT COUNT(*) AS total_users
FROM users;

CREATE OR REPLACE SECURE MATERIALIZED VIEW "PROD"."TEST"."SECURE_USER_COUNT"(
	TOTAL_USERS
) as
SELECT COUNT(*) AS total_users
FROM users;

CREATE OR REPLACE STREAM "PROD"."TEST"."USERS_STREAM"
ON TABLE "PROD"."TEST"."USERS"
APPEND_ONLY = FALSE;

CREATE OR REPLACE TASK DEV_TASK
	OVERLAP_POLICY=NO_OVERLAP
	WAREHOUSE=COMPUTE_WH
	SCHEDULE='USING CRON 0 * * * * UTC'
	AS SELECT CURRENT_TIMESTAMP();

CREATE OR REPLACE TASK REFRESH_USER_DATA
	OVERLAP_POLICY=NO_OVERLAP
	WAREHOUSE=COMPUTE_WH
	SCHEDULE='USING CRON 0 * * * * UTC'
	AS INSERT INTO users (id, name, email, created_at)
    SELECT
        id,
        name,
        email,
        CREATEd_at
    FROM users_stream;

CREATE OR REPLACE ALERT "PROD"."TEST"."HIGH_USER_COUNT_ALERT"
	warehouse=COMPUTE_WH
	schedule='USING CRON 0 * * * * UTC'
	if (exists(
		SELECT 1
        FROM users
        HAVING COUNT(*) > 100000
	))
	then
	INSERT INTO users (id, name, email, created_at)
        VALUES (-1, 'ALERT', 'alert@example.com', CURRENT_TIMESTAMP());


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER FILE FORMAT "PROD"."TEST"."CSV_FORMAT" SET
  FIELD_DELIMITER = DEFAULT
  SKIP_HEADER = 1;
ALTER MASKING POLICY "PROD"."TEST"."EMAIL_MASK" SET BODY ->
CASE
        WHEN CURRENT_ROLE() = 'ACCOUNTADMIN'
        THEN VAL
        ELSE '********'
    END;
CREATE OR REPLACE FUNCTION "PROD"."TEST"."ADD_NUMBERS"("A" NUMBER(38,0), "B" NUMBER(38,0))
RETURNS NUMBER(38,0)
LANGUAGE SQL
AS $$
    A + B
$$;

CREATE OR REPLACE PROCEDURE "PROD"."TEST"."HELLO_USER"("NAME" VARCHAR)
RETURNS VARCHAR
LANGUAGE SQL
EXECUTE AS OWNER
AS $$
BEGIN
    RETURN 'Hello ' || NAME;
END;
$$;

CREATE OR REPLACE VIEW ACTIVE_USERS(
	ID,
	NAME,
	EMAIL
) as
SELECT
    ID,
    NAME,
    EMAIL
FROM USERS
WHERE EMAIL IS NOT NULL;

CREATE OR REPLACE SECURE VIEW SECURE_USERS(
	ID,
	NAME
) as
SELECT
    ID,
    NAME
FROM USERS;

ALTER TAG "PROD"."TEST"."ENVIRONMENT_TAG" SET
  COMMENT = 'Environment tag';

ALTER ALERT "PROD"."TEST"."HIGH_USER_COUNT_ALERT" RESUME;


-- ============================================================
-- END - 41 statement(s)
-- ============================================================