-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.ANALYTICS
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA ANALYTICS;


-- ------------------------------------------------------------
-- DROP CONSTRAINTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."ANALYTICS"."METRIC_DEFINITIONS" DROP CONSTRAINT "UQ_METRIC_CODE";

-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."ANALYTICS"."OBSOLETE_KPI_SNAPSHOTS";
DROP TABLE IF EXISTS "UZAIR_PROD"."ANALYTICS"."LEGACY_REPORTS_ARCHIVE";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_DATA_PIPELINE (
	PIPELINE_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PIPELINE_NAME VARCHAR(200) NOT NULL,
	SOURCE_SCHEMA VARCHAR(100),
	TARGET_SCHEMA VARCHAR(100),
	SCHEDULE VARCHAR(50),
	LAST_RUN_AT TIMESTAMP_NTZ(9),
	LAST_STATUS VARCHAR(20),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_NEW_DATA_PIPELINE primary key (PIPELINE_ID)
);

CREATE OR REPLACE TABLE NEW_DASHBOARD_CONFIG (
	CONFIG_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	DASHBOARD_NAME VARCHAR(200) NOT NULL,
	OWNER_ID NUMBER(10,0),
	IS_PUBLIC BOOLEAN DEFAULT FALSE,
	CONFIG_JSON VARIANT,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint PK_NEW_DASHBOARD_CONFIG primary key (CONFIG_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."ANALYTICS"."REPORT_DEFINITIONS" ADD COLUMN "PARAMETERS" VARIANT;
ALTER TABLE "UZAIR_PROD"."ANALYTICS"."REPORT_DEFINITIONS" ADD COLUMN "SCHEDULE" VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."ANALYTICS"."REPORT_DEFINITIONS" ADD COLUMN "OUTPUT_FORMAT" VARCHAR(20);
ALTER TABLE "UZAIR_PROD"."ANALYTICS"."REPORT_DEFINITIONS" ALTER COLUMN "QUERY_TEXT" SET DATA TYPE VARCHAR(16000);
ALTER TABLE "UZAIR_PROD"."ANALYTICS"."REPORT_DEFINITIONS" ALTER COLUMN "REPORT_NAME" SET DATA TYPE VARCHAR(300);
ALTER TABLE "UZAIR_PROD"."ANALYTICS"."METRIC_DEFINITIONS" ADD CONSTRAINT "UQ_METRIC_CODE" UNIQUE ("METRIC_CODE");
-- NOTE: Column default change on METRIC_DEFINITIONS (PRECISION_SCALE, DATA_TYPE) requires CREATE OR REPLACE
-- Snowflake does not support ALTER COLUMN SET DEFAULT for literal values on any table type.
CREATE OR REPLACE TABLE METRIC_DEFINITIONS (
	METRIC_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	METRIC_NAME VARCHAR(200) NOT NULL,
	METRIC_CODE VARCHAR(50) NOT NULL,
	CALCULATION VARCHAR(4000),
	DATA_TYPE VARCHAR(20) DEFAULT 'NUMBER',
	PRECISION_SCALE NUMBER(3,0) DEFAULT 2,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint UQ_METRIC_CODE unique (METRIC_CODE),
	constraint PK_METRIC_DEFINITIONS primary key (METRIC_ID)
);


-- ============================================================
-- END - 10 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.COMPLIANCE
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA COMPLIANCE;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."COMPLIANCE"."LEGACY_COMPLIANCE_CHECKLIST";
DROP TABLE IF EXISTS "UZAIR_PROD"."COMPLIANCE"."OBSOLETE_BREACH_LOG";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_POLICY (
	POLICY_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	POLICY_NAME VARCHAR(200) NOT NULL,
	POLICY_CODE VARCHAR(50) NOT NULL,
	CATEGORY VARCHAR(100),
	EFFECTIVE_FROM DATE NOT NULL,
	EFFECTIVE_TO DATE,
	OWNER VARCHAR(100),
	VERSION VARCHAR(10) DEFAULT '1.0',
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (POLICY_CODE),
	constraint PK_NEW_POLICY primary key (POLICY_ID)
);

CREATE OR REPLACE TABLE NEW_RISK_REGISTER (
	RISK_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	RISK_NAME VARCHAR(200) NOT NULL,
	CATEGORY VARCHAR(100),
	LIKELIHOOD VARCHAR(20),
	IMPACT VARCHAR(20),
	STATUS VARCHAR(20) DEFAULT 'OPEN',
	OWNER VARCHAR(100),
	REVIEW_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	check (LIKELIHOOD IN ('LOW','MEDIUM','HIGH','CRITICAL')),
	check (IMPACT IN ('LOW','MEDIUM','HIGH','CRITICAL')),
	constraint PK_NEW_RISK_REGISTER primary key (RISK_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."COMPLIANCE"."AUDIT_FINDINGS" ADD COLUMN "REMEDIATION_DUE" DATE;
ALTER TABLE "UZAIR_PROD"."COMPLIANCE"."AUDIT_FINDINGS" ADD COLUMN "RESPONSIBLE_TEAM" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."COMPLIANCE"."AUDIT_FINDINGS" ADD COLUMN "REGULATORY_REF" VARCHAR(200);
ALTER TABLE "UZAIR_PROD"."COMPLIANCE"."AUDIT_FINDINGS" ADD COLUMN "STATUS" VARCHAR(30) DEFAULT 'OPEN';

-- ============================================================
-- END - 8 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.CUSTOMER
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA CUSTOMER;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."CUSTOMER"."LEGACY_CONTACT_HISTORY";
DROP TABLE IF EXISTS "UZAIR_PROD"."CUSTOMER"."OBSOLETE_REWARD_POINTS";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_LOYALTY_PROGRAM (
	PROGRAM_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PROGRAM_NAME VARCHAR(200) NOT NULL,
	TIER_NAME VARCHAR(50) NOT NULL,
	MIN_POINTS NUMBER(10,0) DEFAULT 0,
	MAX_POINTS NUMBER(10,0),
	BENEFITS VARCHAR(2000),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_NEW_LOYALTY_PROGRAM primary key (PROGRAM_ID)
);

CREATE OR REPLACE TABLE NEW_FEEDBACK (
	FEEDBACK_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	CHANNEL VARCHAR(30),
	RATING NUMBER(2,0),
	COMMENTS VARCHAR(4000),
	SUBMITTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	check (CHANNEL IN ('EMAIL','CHAT','PHONE','APP','WEB')),
	check (RATING BETWEEN 1 AND 10),
	constraint PK_NEW_FEEDBACK primary key (FEEDBACK_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_INTERACTIONS" RENAME COLUMN "INT_TYPE" TO "INTERACTION_TYPE";
ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_INTERACTIONS" RENAME COLUMN "INT_DATE" TO "INTERACTION_DATE";
ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_INTERACTIONS" RENAME COLUMN "INT_NOTES" TO "NOTES";
ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_PROFILES" ADD COLUMN "PREFERRED_LANG" VARCHAR(10) DEFAULT 'EN';
ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_PROFILES" ADD COLUMN "SECONDARY_EMAIL" VARCHAR(255);
ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_PROFILES" ADD COLUMN "COMMUNICATION_PREF" VARCHAR(20);
ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_PROFILES" ADD COLUMN "TIMEZONE" VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_PROFILES" ADD COLUMN "IS_VIP" BOOLEAN DEFAULT FALSE;
ALTER TABLE "UZAIR_PROD"."CUSTOMER"."CUSTOMER_PROFILES" ALTER COLUMN "FULL_NAME" SET DATA TYPE VARCHAR(300);

-- ============================================================
-- END - 13 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.FINANCE
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA FINANCE;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."FINANCE"."OLD_TAX_RATES";
DROP TABLE IF EXISTS "UZAIR_PROD"."FINANCE"."LEGACY_JOURNAL_ENTRIES";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_BUDGET_PLAN (
	BUDGET_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	DEPT_CODE VARCHAR(50) NOT NULL,
	FISCAL_YEAR NUMBER(4,0) NOT NULL,
	BUDGET_AMOUNT NUMBER(18,2) NOT NULL,
	APPROVED_BY VARCHAR(100),
	APPROVED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_NEW_BUDGET_PLAN primary key (BUDGET_ID)
);

CREATE OR REPLACE TABLE NEW_EXPENSE_CATEGORY (
	CATEGORY_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CATEGORY_NAME VARCHAR(100) NOT NULL,
	CATEGORY_CODE VARCHAR(20) NOT NULL,
	IS_BILLABLE BOOLEAN DEFAULT FALSE,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	unique (CATEGORY_CODE),
	constraint PK_NEW_EXPENSE_CATEGORY primary key (CATEGORY_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."FINANCE"."INVOICES" ALTER COLUMN "NOTES" SET DATA TYPE VARCHAR(2000);
ALTER TABLE "UZAIR_PROD"."FINANCE"."INVOICES" ALTER COLUMN "TAX_AMOUNT" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."FINANCE"."INVOICES" ALTER COLUMN "INVOICE_NUMBER" SET DATA TYPE VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."FINANCE"."INVOICES" ALTER COLUMN "AMOUNT" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."FINANCE"."EXCHANGE_RATES" ALTER COLUMN "RATE" SET DATA TYPE NUMBER(18,8);
ALTER TABLE "UZAIR_PROD"."FINANCE"."EXCHANGE_RATES" ALTER COLUMN "EFFECTIVE_DATE" SET DATA TYPE DATE;
ALTER TABLE "UZAIR_PROD"."FINANCE"."PAYMENTS" ADD COLUMN "REFERENCE_NO" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."FINANCE"."PAYMENTS" ADD COLUMN "GATEWAY" VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."FINANCE"."PAYMENTS" DROP COLUMN "LEGACY_CODE";

-- ============================================================
-- END - 13 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.HR
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA HR;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."HR"."OBSOLETE_PAYROLL_RUNS";
DROP TABLE IF EXISTS "UZAIR_PROD"."HR"."LEGACY_ATTENDANCE";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_PERFORMANCE_REVIEW (
	REVIEW_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EMPLOYEE_ID NUMBER(10,0) NOT NULL,
	REVIEWER_ID NUMBER(10,0) NOT NULL,
	REVIEW_PERIOD VARCHAR(20) NOT NULL,
	RATING NUMBER(3,1),
	COMMENTS VARCHAR(4000),
	SUBMITTED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	check (RATING BETWEEN 1 AND 5),
	constraint PK_NEW_PERFORMANCE_REVIEW primary key (REVIEW_ID)
);

CREATE OR REPLACE TABLE NEW_TRAINING_PROGRAM (
	PROGRAM_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PROGRAM_NAME VARCHAR(200) NOT NULL,
	PROGRAM_TYPE VARCHAR(50),
	DURATION_HRS NUMBER(6,2),
	IS_MANDATORY BOOLEAN DEFAULT FALSE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	check (PROGRAM_TYPE IN ('ONLINE','IN_PERSON','HYBRID','SELF_PACED')),
	constraint PK_NEW_TRAINING_PROGRAM primary key (PROGRAM_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."HR"."EMPLOYEES" ADD COLUMN "GRADE_LEVEL" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."HR"."EMPLOYEES" ADD COLUMN "WORK_LOCATION" VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."HR"."EMPLOYEES" ADD COLUMN "LINE_MANAGER_ID" NUMBER(10);
ALTER TABLE "UZAIR_PROD"."HR"."EMPLOYEES" ALTER COLUMN "JOB_TITLE" SET DATA TYPE VARCHAR(200);
ALTER TABLE "UZAIR_PROD"."HR"."DEPARTMENTS" ALTER COLUMN "MANAGER_ID" DROP NOT NULL;
ALTER TABLE "UZAIR_PROD"."HR"."DEPARTMENTS" ALTER COLUMN "COST_CENTER" SET NOT NULL;
ALTER TABLE "UZAIR_PROD"."HR"."DEPARTMENTS" ALTER COLUMN "DEPT_NAME" SET DATA TYPE VARCHAR(200);

-- ============================================================
-- END - 11 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.INVENTORY
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA INVENTORY;


-- ------------------------------------------------------------
-- DROP CONSTRAINTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."INVENTORY"."STOCK_MOVEMENTS" DROP PRIMARY KEY;

-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."INVENTORY"."OBSOLETE_REORDER_RULES";
DROP TABLE IF EXISTS "UZAIR_PROD"."INVENTORY"."LEGACY_STOCK_LEDGER";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_WAREHOUSE (
	WAREHOUSE_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	WAREHOUSE_CODE VARCHAR(20) NOT NULL,
	WAREHOUSE_NAME VARCHAR(200) NOT NULL,
	COUNTRY_CODE VARCHAR(3),
	CITY VARCHAR(100),
	CAPACITY_UNITS NUMBER(12,0),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (WAREHOUSE_CODE),
	constraint PK_NEW_WAREHOUSE primary key (WAREHOUSE_ID)
);

CREATE OR REPLACE TABLE NEW_SUPPLIER (
	SUPPLIER_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SUPPLIER_NAME VARCHAR(200) NOT NULL,
	SUPPLIER_CODE VARCHAR(20) NOT NULL,
	CONTACT_EMAIL VARCHAR(255),
	CONTACT_PHONE VARCHAR(30),
	COUNTRY_CODE VARCHAR(3),
	RATING NUMBER(3,1),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (SUPPLIER_CODE),
	check (RATING BETWEEN 1 AND 5),
	constraint PK_NEW_SUPPLIER primary key (SUPPLIER_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."INVENTORY"."PURCHASE_ORDERS" RENAME COLUMN "ORD_DATE" TO "ORDER_DATE";
ALTER TABLE "UZAIR_PROD"."INVENTORY"."PURCHASE_ORDERS" RENAME COLUMN "DLVRY_DATE" TO "DELIVERY_DATE";
ALTER TABLE "UZAIR_PROD"."INVENTORY"."STOCK_ITEMS" ADD COLUMN "BARCODE" VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."INVENTORY"."STOCK_ITEMS" ADD COLUMN "SHELF_LIFE_DAYS" NUMBER(5);
ALTER TABLE "UZAIR_PROD"."INVENTORY"."STOCK_ITEMS" ADD COLUMN "STORAGE_TEMP" VARCHAR(30);
ALTER TABLE "UZAIR_PROD"."INVENTORY"."STOCK_ITEMS" ALTER COLUMN "ITEM_CODE" SET DATA TYPE VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."INVENTORY"."STOCK_ITEMS" ALTER COLUMN "ITEM_NAME" SET DATA TYPE VARCHAR(500);
ALTER TABLE "UZAIR_PROD"."INVENTORY"."STOCK_ITEMS" ALTER COLUMN "UNIT_COST" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."INVENTORY"."STOCK_MOVEMENTS" ADD PRIMARY KEY ("ITEM_ID", "MOVEMENT_DATE", "MOVEMENT_ID");

-- ============================================================
-- END - 14 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.MARKETING
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA MARKETING;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."MARKETING"."LEGACY_MAILING_LIST";
DROP TABLE IF EXISTS "UZAIR_PROD"."MARKETING"."OBSOLETE_PROMO_CODES";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_CAMPAIGN (
	CAMPAIGN_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CAMPAIGN_NAME VARCHAR(200) NOT NULL,
	CAMPAIGN_TYPE VARCHAR(50),
	BUDGET NUMBER(18,2),
	START_DATE DATE,
	END_DATE DATE,
	TARGET_AUDIENCE VARCHAR(200),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	check (CAMPAIGN_TYPE IN ('EMAIL','SMS','SOCIAL','PAID','SEO','EVENT')),
	constraint PK_NEW_CAMPAIGN primary key (CAMPAIGN_ID)
);

CREATE OR REPLACE TABLE NEW_CAMPAIGN_METRICS (
	METRIC_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CAMPAIGN_ID NUMBER(10,0) NOT NULL,
	METRIC_DATE DATE NOT NULL,
	IMPRESSIONS NUMBER(18,0) DEFAULT 0,
	CLICKS NUMBER(18,0) DEFAULT 0,
	CONVERSIONS NUMBER(18,0) DEFAULT 0,
	SPEND NUMBER(18,4) DEFAULT 0,
	REVENUE NUMBER(18,4) DEFAULT 0,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_NEW_CAMPAIGN_METRICS primary key (METRIC_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."MARKETING"."AD_SPEND" ALTER COLUMN "AMOUNT" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MARKETING"."AD_SPEND" ALTER COLUMN "SPEND_DATE" SET DATA TYPE DATE;
ALTER TABLE "UZAIR_PROD"."MARKETING"."EMAIL_SUBSCRIBERS" ADD COLUMN "GDPR_CONSENT" BOOLEAN DEFAULT FALSE;
ALTER TABLE "UZAIR_PROD"."MARKETING"."EMAIL_SUBSCRIBERS" ADD COLUMN "STATUS" VARCHAR(20) DEFAULT 'ACTIVE';
ALTER TABLE "UZAIR_PROD"."MARKETING"."EMAIL_SUBSCRIBERS" ADD COLUMN "PHONE" VARCHAR(30);
ALTER TABLE "UZAIR_PROD"."MARKETING"."EMAIL_SUBSCRIBERS" ADD COLUMN "CONSENT_DATE" TIMESTAMP_NTZ;
ALTER TABLE "UZAIR_PROD"."MARKETING"."EMAIL_SUBSCRIBERS" ADD COLUMN "COUNTRY_CODE" VARCHAR(3);
ALTER TABLE "UZAIR_PROD"."MARKETING"."EMAIL_SUBSCRIBERS" ADD COLUMN "SEGMENT" VARCHAR(50);

-- ============================================================
-- END - 12 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.OPERATIONS
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA OPERATIONS;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."OPERATIONS"."LEGACY_ASSET_REGISTER";
DROP TABLE IF EXISTS "UZAIR_PROD"."OPERATIONS"."OBSOLETE_SHIFT_SCHEDULES";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_SLA_DEFINITION (
	SLA_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SLA_NAME VARCHAR(200) NOT NULL,
	METRIC_TYPE VARCHAR(50),
	TARGET_VALUE NUMBER(10,4),
	UNIT VARCHAR(20),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_NEW_SLA_DEFINITION primary key (SLA_ID)
);

CREATE OR REPLACE TABLE NEW_VENDOR (
	VENDOR_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	VENDOR_NAME VARCHAR(200) NOT NULL,
	VENDOR_CODE VARCHAR(20) NOT NULL,
	SERVICE_TYPE VARCHAR(100),
	CONTRACT_START DATE,
	CONTRACT_END DATE,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (VENDOR_CODE),
	constraint PK_NEW_VENDOR primary key (VENDOR_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."OPERATIONS"."WORK_ORDERS" ADD COLUMN "ACTUAL_HRS" NUMBER(8,2);
ALTER TABLE "UZAIR_PROD"."OPERATIONS"."WORK_ORDERS" ADD COLUMN "ESTIMATED_HRS" NUMBER(8,2);
ALTER TABLE "UZAIR_PROD"."OPERATIONS"."WORK_ORDERS" ADD COLUMN "ROOT_CAUSE" VARCHAR(1000);
ALTER TABLE "UZAIR_PROD"."OPERATIONS"."WORK_ORDERS" ADD COLUMN "ASSIGNED_TEAM" VARCHAR(100);

-- ============================================================
-- END - 8 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.PRODUCT
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA PRODUCT;


-- ------------------------------------------------------------
-- DROP CONSTRAINTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCT_CATEGORIES" DROP PRIMARY KEY;

-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."PRODUCT"."OBSOLETE_PRODUCT_BUNDLES";
DROP TABLE IF EXISTS "UZAIR_PROD"."PRODUCT"."LEGACY_CATALOGUE";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_PRODUCT_VARIANT (
	VARIANT_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PRODUCT_ID NUMBER(10,0) NOT NULL,
	VARIANT_NAME VARCHAR(200) NOT NULL,
	SKU VARCHAR(100) NOT NULL,
	ATTRIBUTES VARIANT,
	STOCK_QTY NUMBER(10,0) DEFAULT 0,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	unique (SKU),
	constraint PK_NEW_PRODUCT_VARIANT primary key (VARIANT_ID)
);

CREATE OR REPLACE TABLE NEW_PRODUCT_REVIEW (
	REVIEW_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	PRODUCT_ID NUMBER(10,0) NOT NULL,
	CUSTOMER_ID NUMBER(10,0),
	RATING NUMBER(2,0),
	TITLE VARCHAR(200),
	BODY VARCHAR(4000),
	IS_VERIFIED BOOLEAN DEFAULT FALSE,
	SUBMITTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	check (RATING BETWEEN 1 AND 5),
	constraint PK_NEW_PRODUCT_REVIEW primary key (REVIEW_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCTS" ADD COLUMN "TAGS" VARCHAR(500);
ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCTS" ADD COLUMN "IS_DIGITAL" BOOLEAN DEFAULT FALSE;
ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCTS" ADD COLUMN "WARRANTY_MONTHS" NUMBER(4);
ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCTS" ADD COLUMN "COUNTRY_OF_ORIGIN" VARCHAR(3);
ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCTS" ALTER COLUMN "PRODUCT_CODE" SET DATA TYPE VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCTS" ALTER COLUMN "PRODUCT_NAME" SET DATA TYPE VARCHAR(500);
ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCTS" ALTER COLUMN "DESCRIPTION" SET DATA TYPE VARCHAR(4000);
ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCTS" ALTER COLUMN "UNIT_PRICE" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."PRODUCT"."PRODUCT_CATEGORIES" ADD PRIMARY KEY ("CATEGORY_CODE", "CATEGORY_ID");
-- NOTE: Column default change on PRODUCT_CATEGORIES (DISPLAY_ORDER) requires CREATE OR REPLACE
-- Snowflake does not support ALTER COLUMN SET DEFAULT for literal values on any table type.
CREATE OR REPLACE TABLE PRODUCT_CATEGORIES (
	CATEGORY_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	CATEGORY_CODE VARCHAR(50) NOT NULL,
	CATEGORY_NAME VARCHAR(200) NOT NULL,
	PARENT_ID NUMBER(10,0),
	DISPLAY_ORDER NUMBER(5,0) DEFAULT 0,
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_PRODUCT_CATEGORIES primary key (CATEGORY_ID, CATEGORY_CODE)
);


-- ============================================================
-- END - 13 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.SALES
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA SALES;


-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."SALES"."OLD_COMMISSION_RATES";
DROP TABLE IF EXISTS "UZAIR_PROD"."SALES"."OBSOLETE_SALES_QUOTES";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_SALES_PIPELINE (
	PIPELINE_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	DEAL_NAME VARCHAR(200) NOT NULL,
	STAGE VARCHAR(50) DEFAULT 'PROSPECTING',
	AMOUNT NUMBER(18,2),
	CLOSE_DATE DATE,
	OWNER_ID NUMBER(10,0),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	check (STAGE IN ('PROSPECTING','QUALIFIED','PROPOSAL','NEGOTIATION','CLOSED_WON','CLOSED_LOST')),
	constraint PK_NEW_SALES_PIPELINE primary key (PIPELINE_ID)
);

CREATE OR REPLACE TABLE NEW_SALES_TARGET (
	TARGET_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	REP_ID NUMBER(10,0) NOT NULL,
	REGION VARCHAR(100) NOT NULL,
	TARGET_AMOUNT NUMBER(18,2) NOT NULL,
	PERIOD VARCHAR(20) NOT NULL,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	constraint PK_NEW_SALES_TARGET primary key (TARGET_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."SALES"."SALES_ORDERS" ADD COLUMN "DISCOUNT_CODE" VARCHAR(30);
ALTER TABLE "UZAIR_PROD"."SALES"."SALES_ORDERS" ADD COLUMN "APPROVED_BY" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."SALES"."SALES_ORDERS" ADD COLUMN "PRIORITY" VARCHAR(20) DEFAULT 'NORMAL';
ALTER TABLE "UZAIR_PROD"."SALES"."SALES_LEADS" RENAME COLUMN "SRC_NAME" TO "LEAD_SOURCE";
ALTER TABLE "UZAIR_PROD"."SALES"."SALES_LEADS" RENAME COLUMN "CUST_NAME" TO "CONTACT_NAME";
ALTER TABLE "UZAIR_PROD"."SALES"."SALES_LEADS" RENAME COLUMN "CUST_EMAIL" TO "CONTACT_EMAIL";
ALTER TABLE "UZAIR_PROD"."SALES"."SALES_REPS" ALTER COLUMN "EMAIL" SET DATA TYPE VARCHAR(255);
ALTER TABLE "UZAIR_PROD"."SALES"."SALES_REPS" ALTER COLUMN "REP_NAME" SET DATA TYPE VARCHAR(200);
ALTER TABLE "UZAIR_PROD"."SALES"."SALES_REPS" ALTER COLUMN "COMMISSION_PCT" SET DATA TYPE NUMBER(8,4);

-- ============================================================
-- END - 13 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.MAIN
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA MAIN;


-- ------------------------------------------------------------
-- DROP CONSTRAINTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" DROP PRIMARY KEY;

-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."LEGACY_CUSTOMER_DATA";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."OBSOLETE_PROMOTIONS";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."DEPRECATED_RATE_CARD";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."OLD_REPORTING_SUMMARY";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_SALES_FACT (
	SALE_ID NUMBER(18,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SALE_DATE DATE NOT NULL,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	PRODUCT_ID NUMBER(10,0) NOT NULL,
	CATEGORY_ID NUMBER(10,0),
	REGION VARCHAR(50),
	COUNTRY_CODE VARCHAR(3),
	QUANTITY NUMBER(10,0) NOT NULL DEFAULT 1,
	UNIT_PRICE NUMBER(18,4) NOT NULL,
	DISCOUNT_PCT NUMBER(6,4) DEFAULT 0,
	GROSS_AMOUNT NUMBER(18,2) NOT NULL,
	DISCOUNT_AMOUNT NUMBER(18,2) DEFAULT 0,
	NET_AMOUNT NUMBER(18,2) NOT NULL,
	TAX_AMOUNT NUMBER(18,2) DEFAULT 0,
	CURRENCY_CODE VARCHAR(3) DEFAULT 'USD',
	PAYMENT_METHOD_ID NUMBER(10,0),
	CHANNEL VARCHAR(50),
	IS_RETURNED BOOLEAN DEFAULT FALSE,
	RETURN_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint PK_NEW_SALES_FACT primary key (SALE_ID)
);

CREATE OR REPLACE TABLE NEW_AUDIT_LOG (
	LOG_ID NUMBER(18,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EVENT_TIME TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TABLE_NAME VARCHAR(200) NOT NULL,
	OPERATION VARCHAR(10) NOT NULL,
	RECORD_ID VARCHAR(100),
	OLD_VALUES VARIANT,
	NEW_VALUES VARIANT,
	CHANGED_BY VARCHAR(100),
	SESSION_ID VARCHAR(100),
	QUERY_ID VARCHAR(100),
	check (OPERATION IN ('INSERT','UPDATE','DELETE','TRUNCATE')),
	constraint PK_NEW_AUDIT_LOG primary key (LOG_ID)
);

CREATE OR REPLACE TABLE NEW_APP_CONFIG (
	CONFIG_KEY VARCHAR(200) NOT NULL,
	CONFIG_VALUE VARCHAR(4000),
	VALUE_TYPE VARCHAR(20) DEFAULT 'STRING',
	ENVIRONMENT VARCHAR(20) NOT NULL DEFAULT 'ALL',
	DESCRIPTION VARCHAR(1000),
	IS_ENCRYPTED BOOLEAN DEFAULT FALSE,
	VALID_FROM DATE DEFAULT CURRENT_DATE(),
	VALID_TO DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_BY VARCHAR(100),
	check (VALUE_TYPE IN ('STRING','NUMBER','BOOLEAN','JSON','DATE')),
	check (ENVIRONMENT IN ('ALL','DEV','UAT','PROD')),
	constraint PK_NEW_APP_CONFIG primary key (CONFIG_KEY, ENVIRONMENT)
);

CREATE OR REPLACE TABLE NEW_PAYMENT_METHOD (
	PAYMENT_METHOD_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	METHOD_NAME VARCHAR(100) NOT NULL,
	METHOD_CODE VARCHAR(20) NOT NULL,
	PROVIDER VARCHAR(100),
	IS_DIGITAL BOOLEAN DEFAULT FALSE,
	PROCESSING_FEE_PCT NUMBER(6,4) DEFAULT 0,
	CURRENCY_CODE VARCHAR(3),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint UQ_PAYMENT_METHOD_CODE unique (METHOD_CODE),
	constraint PK_NEW_PAYMENT_METHOD primary key (PAYMENT_METHOD_ID),
	constraint FK_PAYMENT_CURRENCY foreign key (CURRENCY_CODE) references UZAIR_PROD.MAIN.REF_CURRENCY(CURRENCY_CODE)
);

CREATE OR REPLACE TABLE NEW_CUSTOMER_SEGMENT (
	SEGMENT_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SEGMENT_NAME VARCHAR(200) NOT NULL,
	SEGMENT_CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(1000),
	MIN_REVENUE NUMBER(18,2) DEFAULT 0,
	MAX_REVENUE NUMBER(18,2),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(100),
	unique (SEGMENT_CODE),
	constraint PK_NEW_CUSTOMER_SEGMENT primary key (SEGMENT_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "ADDR_LINE1" TO "ADDRESS_LINE_1";
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "ADDR_LINE2" TO "ADDRESS_LINE_2";
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "CUST_PHONE" TO "PHONE_NUMBER";
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRODUCT_ID" COMMENT 'FK to PRODUCTS table';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "VALID_TO" COMMENT 'Inclusive end date; NULL means open-ended';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICE_AMOUNT" COMMENT 'Price in specified currency';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "VALID_FROM" COMMENT 'Inclusive start date of this price';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "IS_ACTIVE" COMMENT 'Soft delete flag';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICE_TYPE" COMMENT 'Type: LIST, WHOLESALE, PROMO, CONTRACT';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICING_ID" COMMENT 'Surrogate key — auto generated';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "CURRENCY_CODE" COMMENT 'ISO 4217 currency code';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "CREATED_AT" COMMENT 'Record creation timestamp (UTC)';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "MIN_QUANTITY" COMMENT 'Minimum order quantity for this price to apply';
ALTER TABLE "UZAIR_PROD"."MAIN"."FINANCIAL_TRANSACTIONS" ALTER COLUMN "TRANSACTION_DATE" SET DATA TYPE DATE;
ALTER TABLE "UZAIR_PROD"."MAIN"."FINANCIAL_TRANSACTIONS" ALTER COLUMN "AMOUNT" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "LOYALTY_POINTS" NUMBER(10) DEFAULT 0;
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "NATIONALITY" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "LOYALTY_TIER" VARCHAR(20) DEFAULT 'BRONZE';
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "PREFERRED_NAME" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "MIDDLE_NAME" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "REFERRAL_CODE" VARCHAR(20);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "QUANTITY_RESERVED" TO "QUANTITY_ON_HAND";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "QUANTITY_AVAILABLE" TO "QUANTITY_RESERVED";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "LAST_RECEIVED_AT" TO "LAST_COUNTED_AT";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "BIN" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "AISLE" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "LAST_RECEIVED_AT" TIMESTAMP_NTZ;
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "SHELF" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "QUANTITY_AVAILABLE" NUMBER(12) NOT NULL DEFAULT 0;
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "INTERNAL_CODE";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "QUANTITY_ON_HAND";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "LAST_COUNTED_AT";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "LEGACY_REF";
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "PRODUCT_CODE" SET DATA TYPE VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "WEIGHT_KG" SET DATA TYPE NUMBER(10,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "PRODUCT_NAME" SET DATA TYPE VARCHAR(500);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "SKU" SET DATA TYPE VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "DESCRIPTION" SET DATA TYPE VARCHAR(4000);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "COST_PRICE" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "UNIT_PRICE" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" ADD CONSTRAINT "UQ_EMPLOYEE_PRIMARY_ROLE" UNIQUE ("EFFECTIVE_FROM");
ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" ADD PRIMARY KEY ("EFFECTIVE_FROM", "EMPLOYEE_ID", "ROLE_CODE");
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD CONSTRAINT "UQ_INVENTORY_LOC" UNIQUE ("LOCATION_CODE");
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" SET COMMENT = 'Stores time-bounded pricing tiers for products across price types and currencies';
-- NOTE: Column default change on SUPPORT_TICKETS (STATUS) requires CREATE OR REPLACE
-- Snowflake does not support ALTER COLUMN SET DEFAULT for literal values on any table type.
CREATE OR REPLACE TABLE SUPPORT_TICKETS (
	TICKET_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TICKET_NUMBER VARCHAR(30) NOT NULL,
	CUSTOMER_ID NUMBER(10,0),
	SUBJECT VARCHAR(500) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	STATUS VARCHAR(30) DEFAULT 'NEW',
	PRIORITY VARCHAR(20) DEFAULT 'MEDIUM',
	CHANNEL VARCHAR(30),
	ASSIGNED_TO VARCHAR(100),
	RESOLVED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	check (STATUS IN ('NEW','OPEN','IN_PROGRESS','PENDING_CUSTOMER',
                                          'ESCALATED','RESOLVED','CLOSED','CANCELLED')),
	check (PRIORITY IN ('LOW','MEDIUM','HIGH','URGENT','CRITICAL')),
	check (CHANNEL IN ('EMAIL','PHONE','CHAT','PORTAL','SOCIAL','IN_PERSON')),
	constraint UQ_TICKET_NUMBER unique (TICKET_NUMBER),
	constraint PK_SUPPORT_TICKETS primary key (TICKET_ID)
);

-- NOTE: Column default change on ORDERS (STATUS, PRIORITY) requires CREATE OR REPLACE
-- Snowflake does not support ALTER COLUMN SET DEFAULT for literal values on any table type.
CREATE OR REPLACE TABLE ORDERS (
	ORDER_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	ORDER_NUMBER VARCHAR(50) NOT NULL,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	ORDER_DATE TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
	PRIORITY VARCHAR(20) DEFAULT 'NORMAL',
	SHIPPING_ADDRESS VARCHAR(1000) NOT NULL,
	BILLING_ADDRESS VARCHAR(1000),
	CURRENCY_CODE VARCHAR(3) NOT NULL DEFAULT 'USD',
	SUBTOTAL NUMBER(18,2) NOT NULL DEFAULT 0,
	TAX_AMOUNT NUMBER(18,2) DEFAULT 0,
	SHIPPING_AMOUNT NUMBER(18,2) DEFAULT 0,
	TOTAL_AMOUNT NUMBER(18,2) NOT NULL DEFAULT 0,
	NOTES VARCHAR(2000),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint UQ_ORDERS_NUMBER unique (ORDER_NUMBER),
	constraint PK_ORDERS primary key (ORDER_ID),
	constraint FK_ORDERS_CURRENCY foreign key (CURRENCY_CODE) references UZAIR_PROD.MAIN.REF_CURRENCY(CURRENCY_CODE)
);


-- ============================================================
-- END - 56 statement(s)
-- ============================================================

-- ============================================================
-- MIGRATION SCRIPT
-- ============================================================
-- Target: UZAIR_PROD.MAIN
-- ============================================================

USE DATABASE UZAIR_PROD;
USE SCHEMA MAIN;


-- ------------------------------------------------------------
-- DROP CONSTRAINTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" DROP PRIMARY KEY;

-- ------------------------------------------------------------
-- DROP OBJECTS
-- ------------------------------------------------------------

DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."LEGACY_CUSTOMER_DATA";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."OBSOLETE_PROMOTIONS";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."DEPRECATED_RATE_CARD";
DROP TABLE IF EXISTS "UZAIR_PROD"."MAIN"."OLD_REPORTING_SUMMARY";

-- ------------------------------------------------------------
-- CREATE OBJECTS
-- ------------------------------------------------------------

CREATE OR REPLACE TABLE NEW_SALES_FACT (
	SALE_ID NUMBER(18,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SALE_DATE DATE NOT NULL,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	PRODUCT_ID NUMBER(10,0) NOT NULL,
	CATEGORY_ID NUMBER(10,0),
	REGION VARCHAR(50),
	COUNTRY_CODE VARCHAR(3),
	QUANTITY NUMBER(10,0) NOT NULL DEFAULT 1,
	UNIT_PRICE NUMBER(18,4) NOT NULL,
	DISCOUNT_PCT NUMBER(6,4) DEFAULT 0,
	GROSS_AMOUNT NUMBER(18,2) NOT NULL,
	DISCOUNT_AMOUNT NUMBER(18,2) DEFAULT 0,
	NET_AMOUNT NUMBER(18,2) NOT NULL,
	TAX_AMOUNT NUMBER(18,2) DEFAULT 0,
	CURRENCY_CODE VARCHAR(3) DEFAULT 'USD',
	PAYMENT_METHOD_ID NUMBER(10,0),
	CHANNEL VARCHAR(50),
	IS_RETURNED BOOLEAN DEFAULT FALSE,
	RETURN_DATE DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint PK_NEW_SALES_FACT primary key (SALE_ID)
);

CREATE OR REPLACE TABLE NEW_AUDIT_LOG (
	LOG_ID NUMBER(18,0) NOT NULL autoincrement start 1 increment 1 noorder,
	EVENT_TIME TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	TABLE_NAME VARCHAR(200) NOT NULL,
	OPERATION VARCHAR(10) NOT NULL,
	RECORD_ID VARCHAR(100),
	OLD_VALUES VARIANT,
	NEW_VALUES VARIANT,
	CHANGED_BY VARCHAR(100),
	SESSION_ID VARCHAR(100),
	QUERY_ID VARCHAR(100),
	check (OPERATION IN ('INSERT','UPDATE','DELETE','TRUNCATE')),
	constraint PK_NEW_AUDIT_LOG primary key (LOG_ID)
);

CREATE OR REPLACE TABLE NEW_APP_CONFIG (
	CONFIG_KEY VARCHAR(200) NOT NULL,
	CONFIG_VALUE VARCHAR(4000),
	VALUE_TYPE VARCHAR(20) DEFAULT 'STRING',
	ENVIRONMENT VARCHAR(20) NOT NULL DEFAULT 'ALL',
	DESCRIPTION VARCHAR(1000),
	IS_ENCRYPTED BOOLEAN DEFAULT FALSE,
	VALID_FROM DATE DEFAULT CURRENT_DATE(),
	VALID_TO DATE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_BY VARCHAR(100),
	check (VALUE_TYPE IN ('STRING','NUMBER','BOOLEAN','JSON','DATE')),
	check (ENVIRONMENT IN ('ALL','DEV','UAT','PROD')),
	constraint PK_NEW_APP_CONFIG primary key (CONFIG_KEY, ENVIRONMENT)
);

CREATE OR REPLACE TABLE NEW_PAYMENT_METHOD (
	PAYMENT_METHOD_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	METHOD_NAME VARCHAR(100) NOT NULL,
	METHOD_CODE VARCHAR(20) NOT NULL,
	PROVIDER VARCHAR(100),
	IS_DIGITAL BOOLEAN DEFAULT FALSE,
	PROCESSING_FEE_PCT NUMBER(6,4) DEFAULT 0,
	CURRENCY_CODE VARCHAR(3),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint UQ_PAYMENT_METHOD_CODE unique (METHOD_CODE),
	constraint PK_NEW_PAYMENT_METHOD primary key (PAYMENT_METHOD_ID),
	constraint FK_PAYMENT_CURRENCY foreign key (CURRENCY_CODE) references UZAIR_PROD.MAIN.REF_CURRENCY(CURRENCY_CODE)
);

CREATE OR REPLACE TABLE NEW_CUSTOMER_SEGMENT (
	SEGMENT_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	SEGMENT_NAME VARCHAR(200) NOT NULL,
	SEGMENT_CODE VARCHAR(20) NOT NULL,
	DESCRIPTION VARCHAR(1000),
	MIN_REVENUE NUMBER(18,2) DEFAULT 0,
	MAX_REVENUE NUMBER(18,2),
	IS_ACTIVE BOOLEAN DEFAULT TRUE,
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	CREATED_BY VARCHAR(100),
	unique (SEGMENT_CODE),
	constraint PK_NEW_CUSTOMER_SEGMENT primary key (SEGMENT_ID)
);


-- ------------------------------------------------------------
-- ALTER OBJECTS
-- ------------------------------------------------------------

ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "ADDR_LINE1" TO "ADDRESS_LINE_1";
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "ADDR_LINE2" TO "ADDRESS_LINE_2";
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMER_ADDRESSES" RENAME COLUMN "CUST_PHONE" TO "PHONE_NUMBER";
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRODUCT_ID" COMMENT 'FK to PRODUCTS table';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "VALID_TO" COMMENT 'Inclusive end date; NULL means open-ended';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICE_AMOUNT" COMMENT 'Price in specified currency';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "VALID_FROM" COMMENT 'Inclusive start date of this price';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "IS_ACTIVE" COMMENT 'Soft delete flag';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICE_TYPE" COMMENT 'Type: LIST, WHOLESALE, PROMO, CONTRACT';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "PRICING_ID" COMMENT 'Surrogate key — auto generated';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "CURRENCY_CODE" COMMENT 'ISO 4217 currency code';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "CREATED_AT" COMMENT 'Record creation timestamp (UTC)';
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" ALTER COLUMN "MIN_QUANTITY" COMMENT 'Minimum order quantity for this price to apply';
ALTER TABLE "UZAIR_PROD"."MAIN"."FINANCIAL_TRANSACTIONS" ALTER COLUMN "TRANSACTION_DATE" SET DATA TYPE DATE;
ALTER TABLE "UZAIR_PROD"."MAIN"."FINANCIAL_TRANSACTIONS" ALTER COLUMN "AMOUNT" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "LOYALTY_POINTS" NUMBER(10) DEFAULT 0;
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "NATIONALITY" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "LOYALTY_TIER" VARCHAR(20) DEFAULT 'BRONZE';
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "PREFERRED_NAME" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "MIDDLE_NAME" VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."CUSTOMERS" ADD COLUMN "REFERRAL_CODE" VARCHAR(20);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "QUANTITY_RESERVED" TO "QUANTITY_ON_HAND";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "QUANTITY_AVAILABLE" TO "QUANTITY_RESERVED";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" RENAME COLUMN "LAST_RECEIVED_AT" TO "LAST_COUNTED_AT";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "BIN" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "AISLE" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "LAST_RECEIVED_AT" TIMESTAMP_NTZ;
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "SHELF" VARCHAR(10);
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD COLUMN "QUANTITY_AVAILABLE" NUMBER(12) NOT NULL DEFAULT 0;
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "INTERNAL_CODE";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "QUANTITY_ON_HAND";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "LAST_COUNTED_AT";
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" DROP COLUMN "LEGACY_REF";
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "PRODUCT_CODE" SET DATA TYPE VARCHAR(50);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "WEIGHT_KG" SET DATA TYPE NUMBER(10,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "PRODUCT_NAME" SET DATA TYPE VARCHAR(500);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "SKU" SET DATA TYPE VARCHAR(100);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "DESCRIPTION" SET DATA TYPE VARCHAR(4000);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "COST_PRICE" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCTS" ALTER COLUMN "UNIT_PRICE" SET DATA TYPE NUMBER(18,4);
ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" ADD CONSTRAINT "UQ_EMPLOYEE_PRIMARY_ROLE" UNIQUE ("EFFECTIVE_FROM");
ALTER TABLE "UZAIR_PROD"."MAIN"."EMPLOYEE_ROLES" ADD PRIMARY KEY ("EFFECTIVE_FROM", "EMPLOYEE_ID", "ROLE_CODE");
ALTER TABLE "UZAIR_PROD"."MAIN"."INVENTORY" ADD CONSTRAINT "UQ_INVENTORY_LOC" UNIQUE ("LOCATION_CODE");
ALTER TABLE "UZAIR_PROD"."MAIN"."PRODUCT_PRICING" SET COMMENT = 'Stores time-bounded pricing tiers for products across price types and currencies';
-- NOTE: Column default change on SUPPORT_TICKETS (STATUS) requires CREATE OR REPLACE
-- Snowflake does not support ALTER COLUMN SET DEFAULT for literal values on any table type.
CREATE OR REPLACE TABLE SUPPORT_TICKETS (
	TICKET_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	TICKET_NUMBER VARCHAR(30) NOT NULL,
	CUSTOMER_ID NUMBER(10,0),
	SUBJECT VARCHAR(500) NOT NULL,
	DESCRIPTION VARCHAR(4000),
	STATUS VARCHAR(30) DEFAULT 'NEW',
	PRIORITY VARCHAR(20) DEFAULT 'MEDIUM',
	CHANNEL VARCHAR(30),
	ASSIGNED_TO VARCHAR(100),
	RESOLVED_AT TIMESTAMP_NTZ(9),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	check (STATUS IN ('NEW','OPEN','IN_PROGRESS','PENDING_CUSTOMER',
                                          'ESCALATED','RESOLVED','CLOSED','CANCELLED')),
	check (PRIORITY IN ('LOW','MEDIUM','HIGH','URGENT','CRITICAL')),
	check (CHANNEL IN ('EMAIL','PHONE','CHAT','PORTAL','SOCIAL','IN_PERSON')),
	constraint UQ_TICKET_NUMBER unique (TICKET_NUMBER),
	constraint PK_SUPPORT_TICKETS primary key (TICKET_ID)
);

-- NOTE: Column default change on ORDERS (STATUS, PRIORITY) requires CREATE OR REPLACE
-- Snowflake does not support ALTER COLUMN SET DEFAULT for literal values on any table type.
CREATE OR REPLACE TABLE ORDERS (
	ORDER_ID NUMBER(10,0) NOT NULL autoincrement start 1 increment 1 noorder,
	ORDER_NUMBER VARCHAR(50) NOT NULL,
	CUSTOMER_ID NUMBER(10,0) NOT NULL,
	ORDER_DATE TIMESTAMP_NTZ(9) NOT NULL DEFAULT CURRENT_TIMESTAMP(),
	STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
	PRIORITY VARCHAR(20) DEFAULT 'NORMAL',
	SHIPPING_ADDRESS VARCHAR(1000) NOT NULL,
	BILLING_ADDRESS VARCHAR(1000),
	CURRENCY_CODE VARCHAR(3) NOT NULL DEFAULT 'USD',
	SUBTOTAL NUMBER(18,2) NOT NULL DEFAULT 0,
	TAX_AMOUNT NUMBER(18,2) DEFAULT 0,
	SHIPPING_AMOUNT NUMBER(18,2) DEFAULT 0,
	TOTAL_AMOUNT NUMBER(18,2) NOT NULL DEFAULT 0,
	NOTES VARCHAR(2000),
	CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
	UPDATED_AT TIMESTAMP_NTZ(9),
	constraint UQ_ORDERS_NUMBER unique (ORDER_NUMBER),
	constraint PK_ORDERS primary key (ORDER_ID),
	constraint FK_ORDERS_CURRENCY foreign key (CURRENCY_CODE) references UZAIR_PROD.MAIN.REF_CURRENCY(CURRENCY_CODE)
);


-- ============================================================
-- END - 56 statement(s)
-- ============================================================